### ISSUE TITLE
Generar un Resumen de Base de Datos

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/ISPC-proyecto-integrador#2]
Glosario.
Videos en YouTube relacionados.
Links con información importante.

**Comment by JohnJoshepSalinas** [comment]
RESUMEN
UN POCO DE HISTORIA DE BASE DE DATOS
“Un modelo relacional de datos para grandes bancos de datos compartidos”. ORACLE

SQL (Structured Query Language) o lo que es lo mismo un lenguaje de consultas o lenguaje declarativo de acceso a bases de datos relacionales que permite efectuar consultas con el fin de recuperar información de interés de una base de datos y hacer cambios sobre la base de datos.

La utilización de lenguajes como C++ o Java requiere que los SGBD relacionales se adapten a ellos con interfaces adecuadas.

INTRO
Ventajas
 Independencia de los datos y los programas y procesos. Esto permite modificar los datos
sin modificar el código de las aplicaciones.
 Menor redundancia. No hace falta tanta repetición de datos. Sólo se indica la forma en la que se
relacionan los datos.
 Integridad de los datos. Mayor dificultad de perder los datos o de realizar incoherencias con
ellos.
 Mayor seguridad en los datos. Al permitir limitar el acceso a los usuarios. Cada tipo de usuario podrá acceder a unas cosas.
 Datos más documentados. Gracias a los metadatos que permiten describir la información de la base de datos.
 Acceso a los datos más eficiente. La organización de los datos produce un resultado más
óptimo en rendimiento.
 Menor espacio de almacenamiento. Gracias a una mejor estructuración de los datos.
 Acceso simultáneo a los datos. Es más fácil controlar el acceso de usuarios de forma concurrente.

Los esquemas externos los realizan las programadoras/es según las indicaciones formales de los y las analistas.

                           Formas de ejecución de un SGBD

Hay tres posibilidades de funcionamiento:

SGBDs monocapa: Es la más sencilla, pero la que tiene menos escalabilidad (posibilidad de crecer). El Sistema Gestor se instala en una máquina y los usuarios acceden directamente a esa máquina y ese Sistema Gestor. En estos sistemas no se accede de forma remota a la base de datos.

SGBDs bicapa: Estructura clásica, la base de datos y su SGBD están en un servidor al cual acceden los clientes. El cliente posee software que permite al usuario enviar instrucciones al SGBD en el servidor y recibir los resultados de estas instrucciones. Para ello el software cliente y el servidor deben utilizar software de comunicaciones en red.
Hay dos posibilidades:
 Estructura Cliente-Servidor. La base de datos está en un solo servidor al que acceden los clientes (incluso simultáneamente).
 Cliente Multi-servidor. En este caso los clientes acceden a un conjunto de servidores que
distribuyen la base de datos. El cliente no sabe si los datos están en uno o más servidores, ya que el resultado es el mismo independientemente de dónde se almacenan los datos. Se usa cuando el número de clientes ha crecido mucho y un solo servidor no podría atender sus peticiones.

SGBD de tres o más capas: Es una estructura de tipo cliente/servidor, pero en la que hay al menos una capa intermedia entre las dos. Esa capa se suele encargar de procesar las peticiones y enviarlas al SGBD con el que se comunica. Un ejemplo habitual es que la tercer capa sea un servidor web que evita que el cliente se conecte directamente al SGBD. Ese servidor web se encarga de traducir lo que el cliente realiza a una forma entendible por la base de datos.
Esta forma de trabajar permite además que para usar una base de datos, baste un simple navegador al cliente.
Puede haber más capas con otros fines. Estas capas siempre están entre el cliente y el servidor.

                                       MODELOS

Cada SGBD puede utilizar un modelo diferente para los datos. Por lo que hay modelos conceptuales diferentes:

           Diferencias entre el modelo lógico y el conceptual:

El modelo conceptual es independiente del DBMS que se vaya a utilizar.
El lógico depende de un tipo de SGBD en particular.
El modelo lógico está más cerca del modelo físico, el que utiliza internamente el ordenador.
El modelo conceptual es el más cercano al usuario, el lógico es el encargado de establecer el paso entre el modelo conceptual y el modelo físico del sistema.

ejemplos de modelos conceptuales son:
 Modelo Entidad Relación
 Modelo RM/T
 Modelo UML
Ejemplos de modelos lógicos son:
 Modelo relacional
 Modelo Codasyl
 Modelo Jerárquico

                               Modelo relacional.

En este modelo los datos se organizan en tablas cuyos datos se relacionan. Es el modelo más popular.

        Bases de datos objeto-relacionales

Se basan en el estándar SQL 99. En ese estándar se añade a las bases
relacionales la posibilidad de almacenar procedimientos de usuario, triggers, tipos definidos por el usuario, consultas recursivas, bases de datos OLAP, tipos LOB,...
Las últimas versiones de la mayoría de las clásicas grandes bases de datos relacionales (Oracle, SQL Server, Informix, ...) son objeto relacionales.

                     Bases de datos NoSQL.

Bajo este nombre se agrupan las bases de datos (con arquitecturas muy diversas) pensadas para grabar los datos de manera veloz para así poder atender a miles y miles de peticiones.
