### ISSUE TITLE
Resumen MySql

### ISSUE THREAD

**Issue by IgnacioCarnero** [IgnacioCarnero/ISPC-proyecto-integrador#4]
Ingresar conceptos mas importantes de MySql.
Como crear tablas.
Como realizar consultas a tablas.

**Comment by JohnJoshepSalinas** [comment]
CREACION
(EN ESTA  MIRADA)
      La sentencia básica de MySQL que se utiliza para crear una tabla es create table su función es crear una tabla con las características que le indiquemos seguidamente del comando en referencia.

      Los parámetros “Nombre_Columna” especifican los nombres de las columnas que integran las tablas.

Los parámetros “Tipo_de_Dato” especifican que tipo de datos admitirá esa columna (ej. varchar, integer, decimal, date, etc.).

El parámetro “Longitud” especifica la longitud máxima de caracteres que admitirá la columna de la tabla.

Cabe aclarar que hay varias propiedades que pueden ser aplicadas a las columnas de la tabla, por ejemplo una de las más comunes es primary key, la cual nos permite indicar que columna será llave primaria, también podemos establecer que alguna columna no acepte valores nulos, a través de la propiedad not null.

Existe otra forma de crear tablas sin necesidad de usar código o script de la Base de Datos, esto se realiza a través de MySql Workbench que a través de sus funciones nos facilita realizar esta tarea.

Los siguientes tipos de restriccion son válidos: 
* NOT NULL
*UNIQUE
*PRIMARY KEY
*FOREIGN KEY
*CHECK

MODIFICACIÓN

Agregar campos nuevos

Puedes agregar un nuevo campo usando el comando ALTER TABLE con la cláusula ADD COLUMN. Por ejemplo, vamos a agregar el campo first_name a nuestra tabla employees:

MariaDB [storage]> ALTER TABLE employees ADD COLUMN first_name VARCHAR(100);

El comando ALTER TABLE va seguido del nombre de la tabla, luego de la cláusula ADD COLUMN y por último la definición del campo, es decir, el nombre del campo seguido del tipo de dato y sus restricciones (así como cuando creaste la tabla).

Por defecto, los campos se agregarán al final, pero también puedes agregarlos en una posición específica, usando FIRST para añadirlos al inicio o AFTER para añadirlos después de otro campo.

Renombrar un campo

Puedes cambiar el nombre de un campo usando el comando ALTER TABLE con la cláusula CHANGE COLUMN. Por ejemplo, vamos a renombrar el campo name a last_name:

MariaDB [storage]> ALTER TABLE employees CHANGE COLUMN name last_name VARCHAR(150);

La cláusula CHANGE COLUMN te pide que especifiques el nombre actual del campo y luego el nuevo nombre que darás a ese campo, seguido del tipo de dato y las restricciones (en caso de tenerlas).

Aunque solo desees cambiar el nombre del campo, si usas la cláusula CHANGE COLUMN debes especificar su definición, ya que ésta también será modificada.

Cambiar tipo de datos y/o restricciones

El comando ALTER TABLE con la cláusula MODIFY COLUMN nos permite cambiar el tipo de dato y/o restricciones de un campo, solo basta con colocar su nombre y su nueva definición:

MariaDB [storage]> ALTER TABLE employees MODIFY COLUMN last_name VARCHAR(100);

Aunque usando la cláusula CHANGE COLUMN también puedes lograr esto, la cláusula MODIFY COLUMN es la más recomendable si solo deseas cambiar la definición de un campo.

Eliminar campos

Para eliminar un campo debes usar el comando ALTER TABLE seguido del nombre de la tabla, luego la cláusula DROP COLUMN y por último el nombre del campo que deseas eliminar. Por ejemplo:

MariaDB [storage]> ALTER TABLE employees DROP COLUMN email;

Si ejecutamos el comando DESC employees, veremos que el campo email no está.

Recuerda que cuando eliminas un campo también borras la información almacenada en éste.

**Comment by JohnJoshepSalinas** [comment]
CREACION
(EN ESTA  MIRADA)
      La sentencia básica de MySQL que se utiliza para crear una tabla es create table su función es crear una tabla con las características que le indiquemos seguidamente del comando en referencia.

      Los parámetros “Nombre_Columna” especifican los nombres de las columnas que integran las tablas.

Los parámetros “Tipo_de_Dato” especifican que tipo de datos admitirá esa columna (ej. varchar, integer, decimal, date, etc.).

El parámetro “Longitud” especifica la longitud máxima de caracteres que admitirá la columna de la tabla.

Cabe aclarar que hay varias propiedades que pueden ser aplicadas a las columnas de la tabla, por ejemplo una de las más comunes es primary key, la cual nos permite indicar que columna será llave primaria, también podemos establecer que alguna columna no acepte valores nulos, a través de la propiedad not null.

Existe otra forma de crear tablas sin necesidad de usar código o script de la Base de Datos, esto se realiza a través de MySql Workbench que a través de sus funciones nos facilita realizar esta tarea.

Los siguientes tipos de restriccion son válidos: 
* NOT NULL
*UNIQUE
*PRIMARY KEY
*FOREIGN KEY
*CHECK

MODIFICACIÓN

Agregar campos nuevos

Puedes agregar un nuevo campo usando el comando ALTER TABLE con la cláusula ADD COLUMN. Por ejemplo, vamos a agregar el campo first_name a nuestra tabla employees:

MariaDB [storage]> ALTER TABLE employees ADD COLUMN first_name VARCHAR(100);

El comando ALTER TABLE va seguido del nombre de la tabla, luego de la cláusula ADD COLUMN y por último la definición del campo, es decir, el nombre del campo seguido del tipo de dato y sus restricciones (así como cuando creaste la tabla).

Por defecto, los campos se agregarán al final, pero también puedes agregarlos en una posición específica, usando FIRST para añadirlos al inicio o AFTER para añadirlos después de otro campo.

Renombrar un campo

Puedes cambiar el nombre de un campo usando el comando ALTER TABLE con la cláusula CHANGE COLUMN. Por ejemplo, vamos a renombrar el campo name a last_name:

MariaDB [storage]> ALTER TABLE employees CHANGE COLUMN name last_name VARCHAR(150);

La cláusula CHANGE COLUMN te pide que especifiques el nombre actual del campo y luego el nuevo nombre que darás a ese campo, seguido del tipo de dato y las restricciones (en caso de tenerlas).

Aunque solo desees cambiar el nombre del campo, si usas la cláusula CHANGE COLUMN debes especificar su definición, ya que ésta también será modificada.

Cambiar tipo de datos y/o restricciones

El comando ALTER TABLE con la cláusula MODIFY COLUMN nos permite cambiar el tipo de dato y/o restricciones de un campo, solo basta con colocar su nombre y su nueva definición:

MariaDB [storage]> ALTER TABLE employees MODIFY COLUMN last_name VARCHAR(100);

Aunque usando la cláusula CHANGE COLUMN también puedes lograr esto, la cláusula MODIFY COLUMN es la más recomendable si solo deseas cambiar la definición de un campo.

Eliminar campos

Para eliminar un campo debes usar el comando ALTER TABLE seguido del nombre de la tabla, luego la cláusula DROP COLUMN y por último el nombre del campo que deseas eliminar. Por ejemplo:

MariaDB [storage]> ALTER TABLE employees DROP COLUMN email;

Si ejecutamos el comando DESC employees, veremos que el campo email no está.

Recuerda que cuando eliminas un campo también borras la información almacenada en éste.
